source 'http://rubygems.org'

gem 'rails', '5.2.1'
gem 'sqlite3', '~> 1.3', '< 1.4'

gem 'json'
gem 'jquery-rails'
gem 'jquery-ui-rails'

gem "haml-rails", "~> 2.0"

gem 'awesome_nested_set', github: "collectiveidea/awesome_nested_set"
gem 'the_sortable_tree', path: '../../'
# gem 'the_sortable_tree', '2.6.1'

group :assets do
  gem 'uglifier'
  gem 'coffee-rails'
end

group :development, :test do
  gem 'faker'
  gem 'pry'

  gem 'rspec'
  gem 'rspec-core'
  gem 'rspec-rails'
  gem 'rspec-mocks'
  gem 'rspec-expectations'

  gem 'capybara'
  gem 'selenium-webdriver'
end

group :test do
  gem 'factory_girl'
  gem 'database_cleaner'
end
